/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './src/**/*.html',
    './src/**/*.js',
  ],
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
  theme: {
    extend: {
      colors: {
        'charcoal-text': '#1A1A1A',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#83d7b4',
        'surface-variant': '#e4e2dd',
        'on-background': '#1b1c19',
        'on-surface': '#1b1c19',
        'inverse-on-surface': '#f2f1ec',
        'truck-art-blue': '#0096FF',
        'on-primary-container': '#92e7c3',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#ffb4aa',
        'inverse-primary': '#83d7b4',
        'surface-tint': '#046c50',
        'secondary-fixed': '#ffe088',
        'on-secondary': '#ffffff',
        'surface-dim': '#dbdad5',
        'on-secondary-fixed-variant': '#574500',
        'tertiary-fixed': '#ffdad5',
        'on-surface-variant': '#3f4944',
        'on-primary-fixed-variant': '#00513b',
        'on-tertiary-container': '#ffcac3',
        'secondary-container': '#fed65b',
        'deep-emerald': '#006A4E',
        'on-secondary-container': '#745c00',
        'surface-container': '#f0eee9',
        'outline-variant': '#bec9c2',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#75322b',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#3c0705',
        'metallic-gold': '#D4AF37',
        'secondary-fixed-dim': '#e9c349',
        'primary-container': '#006a4e',
        outline: '#6f7a73',
        'on-secondary-fixed': '#241a00',
        'on-primary': '#ffffff',
        'surface-bright': '#fbf9f4',
        tertiary: '#74302a',
        'truck-art-orange': '#FF8C00',
        'surface-container-high': '#eae8e3',
        'on-tertiary': '#ffffff',
        'cream-canvas': '#F9F7F2',
        secondary: '#735c00',
        'surface-container-highest': '#e4e2dd',
        background: '#fbf9f4',
        'primary-fixed': '#9ef4d0',
        'surface-container-low': '#f5f3ee',
        'on-primary-fixed': '#002116',
        'error-container': '#ffdad6',
        'tertiary-container': '#91473f',
        'inverse-surface': '#30312e',
        primary: '#00503a',
        surface: '#fbf9f4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '0.5rem',
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'stack-md': '1.5rem',
        'margin-desktop': '5rem',
        'section-gap': '4rem',
      },
      fontFamily: {
        'headline-lg': ['Bodoni Moda', 'serif'],
        'display-hero-mobile': ['Bodoni Moda', 'serif'],
        'headline-md': ['Bodoni Moda', 'serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'display-hero': ['Bodoni Moda', 'serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-hero-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-hero': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
      },
    },
  },
};
